/**
 * A set of controls for the HW4 keybinding
 */
export const AAControls = {
    MOVE_LEFT: "MOVE_LEFT",
    MOVE_RIGHT: "MOVE_RIGHT",
    JUMP: "JUMP",
    ATTACK: "ATTACK",
    SELECT_TONGUE: "SELECT_TONGUE",
    SELECT_FIREBALL: "SELECT_FIREBALL",
    SELECT_ICE: "SELECT_ICE",
    PAUSE: "PAUSE",
    GOTO_BOSS: "GOTO_BOSS",
    TOGGLE_INVINCIBILITY: "TOGGLE_INVINCIBILITY",
    PLAYER_KILL: "PLAYER_KILL",

    // FOR GOTO LEVEL/BOSS
    GOTO_LEVEL_1: "GOTO_LEVEL_1",
    GOTO_LEVEL_2: "GOTO_LEVEL_2",
    GOTO_LEVEL_3: "GOTO_LEVEL_3",
    GOTO_LEVEL_4: "GOTO_LEVEL_4",
    GOTO_LEVEL_5: "GOTO_LEVEL_5",
    GOTO_LEVEL_6: "GOTO_LEVEL_6",
} as const;